### ISSUE TITLE
Searchbar

### ISSUE THREAD

**Issue by jensensitve** [jensensitve/Gruppe5#6]
Hey nice work all. But we have a problem. We have a x scrollbar. Problem is the  10rem left. In the searchbar its pushing out the container to the right. Could someone pls fix that!

 
![searchbar-scrollbar](https://user-images.githubusercontent.com/117394801/207848128-41dc4c69-679b-455f-a357-d0668e0552ad.jpg)

**Comment by uluskarakoc** [comment]
gerne

**Comment by jensensitve** [comment]
fixed on my self  the last tiny thing -> nice weekend.
